name: Build and Release Extension

# 当创建并推送一个新的 tag 时触发
on:
  push:
    tags:
      - 'v*' # 匹配所有以 "v" 开头的 tag，例如 v1.0.0, v0.5.2-beta

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # 授予工作流程写权限，以便创建 Release

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 PNPM
      - name: Set up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 第三步：设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 第四步：安装依赖
      - name: Install dependencies
        run: pnpm install

      # 第五步：构建并打包插件
      - name: Build and Zip Extension
        run: pnpm zip

      # 第六步：创建 GitHub Release 并上传产物
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # files 字段指定了要上传的文件路径
          # a/* 匹配所有 zip 和 xpi 文件
          files: |
            ./*.zip
            ./*.xpi
